### Get authorization code
https://sandbox.procore.com/oauth/authorize?
response_type=code&
client_id=XeaKmKpVBCw-Zw_zHnHDCrLFYWWnHY1AHEpMoZ8LaSQ&
redirect_uri=http://localhost&

### Get access token using code (Expires after 1.5 hours)
curl -X POST https://sandbox.procore.com/oauth/token \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "grant_type=authorization_code&client_id=XeaKmKpVBCw-Zw_zHnHDCrLFYWWnHY1AHEpMoZ8LaSQ&client_secret=Tsx2DCVxIYfxSvYw185SFJlAnFyTrsy86lg_-t--G8I&code=P02WUoMZydw0SJGIexGUIRKUPBkcMGG3FB-pmWGPPLY&redirect_uri=http://localhost"

### Get infomration about the user associated with this token
GET https://sandbox.procore.com/rest/v1.0/me
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg

### Get companies in sandbox
GET https://sandbox.procore.com/rest/v1.0/companies/
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg

### Get projects in company
GET https://sandbox.procore.com/rest/v1.0/companies/4268200/projects
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg

### Get delivery logs in project
GET https://sandbox.procore.com/rest/v1.0/projects/126842/delivery_logs
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg

### Create delivery log in project
POST https://sandbox.procore.com/rest/v1.0/projects/126842/delivery_logs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg
Procore-Company-Id: 4268200

{
    "delivery_log": {
        "time_hour": 0,
        "time_minute": 0
    }
}

### Get productivity logs in project
GET https://sandbox.procore.com/rest/v1.0/projects/126842/productivity_logs
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg

### Create productivity log in project
POST https://sandbox.procore.com/rest/v1.0/projects/126842/productivity_logs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg
Procore-Company-Id: 4268200

{
    "productivity_log": {
        "line_item_id": 805113
    }
}

### Get contracts in project
GET https://sandbox.procore.com/rest/v1.0/purchase_order_contracts?project_id=126842
Authorization: Bearer eyJhbGciOiJFUzUxMiJ9.eyJhbXIiOltdLCJhaWQiOiJYZWFLbUtwVkJDdy1ad196SG5IRENyTEZZV1duSFkxQUhFcE1vWjhMYVNRIiwiYW91aWQiOjE0MDcwOCwiYW91dWlkIjoiZDBhNDg0ZjYtOWI0MC00ODI0LWJiMjctMjJiNGE1ODdiN2Q3IiwiZXhwIjoxNzMyMTE3MTc0LCJzaWF0IjoxNzMyMDQ2Njc4LCJ1aWQiOjE0MDcwNywidXVpZCI6Ijc1OTkxZmJhLTA3MjctNDc5NC1hNzdhLTQwOGFmYmQ3OTZjNSIsImxhc3RfbWZhX2NoZWNrIjoxNzMyMTExNzc0fQ.AGkUadMm_0iIDpO7zkZJVv2U51RQzjNe8T51NjnhH6OQO_A5PGLsDZzYZnGC3p2vffqjAHPNkJmhqkhlaSWtSYLWAQRvHqg0LnapSNF9jMHWEbUrV6HzfvTn2cvZ8WjkCY9i3Q3a_KyczrCSYCG3-Z5q8UcDKXdRCrgfWwR2L24KoShg
Procore-Company-Id: 4268200

